application: aerobic-star-94919
version: 2
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: project4.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
